log = stdout
loglevel = warn

ipv4 = true
ipv6 = true
nat = false
port = 24688
notransit = true
bandwidth = O

[ntcp2]
enabled = true
published = true

[ssu2]
enabled = true
published = true

[upnp]
enabled = false

[http]
enabled = true
address = 127.0.0.1
port = 7070

[httpproxy]
enabled = false

[socksproxy]
enabled = false

[sam]
enabled = false

[bob]
enabled = false

[i2cp]
enabled = false
