[avkean]
type = http
host = web
port = 80
keys = keys/avkean-i2p-keys.dat
signaturetype = 7
inbound.length = 1
outbound.length = 1
inbound.quantity = 5
outbound.quantity = 5
i2cp.leaseSetEncType = 4
i2pheaders = false

[avkean-statsi2p]
type = http
host = web
port = 80
keys = keys/avkean-i2p-keys-old2.dat
signaturetype = 7
inbound.length = 1
outbound.length = 1
inbound.quantity = 5
outbound.quantity = 5
i2cp.leaseSetEncType = 4
i2pheaders = false
